config/routes.rb
Rails.application.routes.draw do
  resources :diaries, only: [:new, :create, :index, :show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  devise_for :users
  resources :diaries
  root 'diaries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user

  # Active Storageで画像を1枚添付
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_secure_password

  has_many :diaries, dependent: :destroy # User モデルと Diary モデルの関連付け（後で戻します）

  # バリデーションを設定
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  # パスワードの長さを8文字以上にする
  validates :password, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user = current_user

    if @diary.save
      redirect_to diaries_path
    else
      render :new
    end
  end

  def index
    @diaries = Diary.order(created_at: :desc)
    @diaries = Diary.all
  end

  def show
  end

  def edit
  end

  def update
    if params[:diary][:remove_image] == '1'
      @diary.image.purge
    end

    if @diary.update(diary_params.except(:remove_image))
      # redirect_to diaries_path(@diary)
      redirect_to diaries_path
    else
      render :edit
    end
  end

  def destroy
    @diary.destroy
    redirect_to diaries_path
  end

  private

  def set_diary
    @diary = Diary.find(params[:id])
  end

  def diary_params
    params.require(:diary).permit(:title, :image, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/create.html.erb
<h1>Diaries#create</h1>
<p>Find me in app/views/diaries/create.html.erb</p>

app/views/diaries/edit.html.erb
<h1>日記の編集</h1>

<%= form_with model: @diary, local: true, html: { multipart: true, data: { turbo: false } } do |f| %>
  <% if @diary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% @diary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :image, "画像" %><br>
    <%= f.file_field :image %>
    <% if @diary.image.attached? %>
      <div>
        <%= image_tag @diary.image, style: 'max-width: 300px;' %><br>
        <%= f.check_box :remove_image %> <%= f.label :remove_image, "画像を削除" %>
      </div>
    <% end %>
  </div>

  <div>
    <%= f.label :text, "コメント" %><br>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.submit "更新する" %>
  </div>
<% end %>

<div>
  <%= link_to "詳細に戻る", @diary %> |
  <%= link_to "一覧に戻る", diaries_path %>
</div>

app/views/diaries/index.html.erb
<h1>Diaries#index</h1>
<p>Find me in app/views/diaries/index.html.erb</p>

<h1>投稿一覧</h1>
<% @diaries.each do |diary| %>
  <div class="diary">
    <h2><%= diary.title %></h2>
    <% if diary.image.attached? %>
      <%= image_tag diary.image, width: 300 %>
    <% end %>

    <p><%= diary.text.truncate(30) %></p>
    <%= link_to '続きを読む', diary_path(diary) %>
    <br>

    <%= link_to "編集", edit_diary_path(diary) %>
    <%= button_to "削除", diary_path(diary), method: :delete %>
    <hr>
  </div>
<% end %>
<%= link_to "日記を作成", new_diary_path %>

app/views/diaries/new.html.erb
<h1>Diaries#new</h1>
<p>Find me in app/views/diaries/new.html.erb</p>

<h1>旅の思い出を記す</h1>

<%= form_with model: @diary, local: true, html: { multipart: true, data: { turbo: false } } do|f| %>
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :image, "画像" %><br>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.label :text, "コメント" %><br>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.submit "記録する" %><br>
  </div>
<% end %>

app/views/diaries/show.html.erb
<h1>Diaries#show</h1>
<p>Find me in app/views/diaries/show.html.erb</p>

<h1><%= @diary.title %></h1>

<% if @diary.image.attached? %>
  <%= image_tag @diary.image %>
<% end %>

<p><%= simple_format(@diary.text) %></p>

<p>作成日時: <%= l @diary.created_at, format: :long %></p>
<p>更新日時: <%= l @diary.updated_at, format: :long %></p>

<%= link_to '編集', edit_diary_path(@diary) %>
<%= button_to "削除", diary_path(@diary), method: :delete %>
<%= link_to '一覧に戻る', diaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Memori Log" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>